### PR TITLE
Fix android ci builds and enable them again

### PR DESCRIPTION
**Pull request by JBou**
Motivation:

We need to use NDK version of 23 or newer as otherwise cargo will fail

Modifications:

Use NDK version 25
Update environment variables for Autoconf build system android build as stated on https://developer.android.com/ndk/guides/other_build_systems

Result:

Android build works again

### CODE REVIEW

**Comment by JBou** [comment]
I saw that on [this line](https://github.com/netty/netty-incubator-codec-quic/pull/553/files#diff-68ba9d12f6f2601fe3c9f7f9d0d02aaea52384559d6d08fae7afc941663fdfcdL212) in `ci-build.yml` the cache key starts with `pr-` prefix. Should we remove it?

**Comment by normanmaurer** [comment]
@JBou yes thanks

**Comment by JBou** [comment]
Alright, I fixed it

**Comment by normanmaurer** [comment]
@JBou thanks!

**Pull request merged**
